## Numpy 

In [1]:
import numpy as np

In [2]:
a = np.arange(20)
b = list(range(30))

In [3]:
print(a) 
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [9]:
a = np.arange(15).reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(3, 5)
15
int32
4
<class 'numpy.ndarray'>


In [12]:
#help(a)

In [13]:
x = np.array( [1.0,2.0,3.0,4.0] )
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float64


In [14]:
y = np.eye(10)
dtype = np.float64
y

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
z = np.linspace(-1 , 2 , 15 , endpoint=True)
print(z)

[-1.         -0.78571429 -0.57142857 -0.35714286 -0.14285714  0.07142857
  0.28571429  0.5         0.71428571  0.92857143  1.14285714  1.35714286
  1.57142857  1.78571429  2.        ]


In [26]:
z.reshape(3,5)

array([[-1.        , -0.78571429, -0.57142857, -0.35714286, -0.14285714],
       [ 0.07142857,  0.28571429,  0.5       ,  0.71428571,  0.92857143],
       [ 1.14285714,  1.35714286,  1.57142857,  1.78571429,  2.        ]])

In [27]:
f = np.logspace(-1 , 2 , 15 , endpoint=True, base=10)
print(f)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [28]:
g = np.fromfunction(lambda i, j: i==j, (3,3), dtype=int)
g

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

## Array Operations

In [35]:
a = np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [36]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [37]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [38]:
a*a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [43]:
b = a.transpose()
b

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [52]:
print(a);print('*');print(b)
print(a @ b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
*
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
[[  14   38   62   86  110  134]
 [  38  126  214  302  390  478]
 [  62  214  366  518  670  822]
 [  86  302  518  734  950 1166]
 [ 110  390  670  950 1230 1510]
 [ 134  478  822 1166 1510 1854]]


In [53]:
a.sum(axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [54]:
a.sum()

276

In [55]:
print(a.min() , a.max())

0 23


### Universal function

In [56]:
b = a*np.pi/12
print(b)

[[0.         0.26179939 0.52359878 0.78539816]
 [1.04719755 1.30899694 1.57079633 1.83259571]
 [2.0943951  2.35619449 2.61799388 2.87979327]
 [3.14159265 3.40339204 3.66519143 3.92699082]
 [4.1887902  4.45058959 4.71238898 4.97418837]
 [5.23598776 5.49778714 5.75958653 6.02138592]]


In [57]:
c = np.cos(b)

In [58]:
print(c)

[[ 1.00000000e+00  9.65925826e-01  8.66025404e-01  7.07106781e-01]
 [ 5.00000000e-01  2.58819045e-01  6.12323400e-17 -2.58819045e-01]
 [-5.00000000e-01 -7.07106781e-01 -8.66025404e-01 -9.65925826e-01]
 [-1.00000000e+00 -9.65925826e-01 -8.66025404e-01 -7.07106781e-01]
 [-5.00000000e-01 -2.58819045e-01 -1.83697020e-16  2.58819045e-01]
 [ 5.00000000e-01  7.07106781e-01  8.66025404e-01  9.65925826e-01]]


In [59]:
d = b + c

In [60]:
d

array([[1.        , 1.22772521, 1.38962418, 1.49250494],
       [1.54719755, 1.56781598, 1.57079633, 1.57377667],
       [1.5943951 , 1.64908771, 1.75196847, 1.91386744],
       [2.14159265, 2.43746622, 2.79916603, 3.21988404],
       [3.6887902 , 4.19177055, 4.71238898, 5.23300741],
       [5.73598776, 6.20489392, 6.62561194, 6.98731175]])

### Array slicing

In [65]:
v = np.arange(9)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
v[3]

3

In [67]:
print(v[2:3])

[2]


In [81]:
im = np.arange(1000)

In [82]:
im

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [87]:
even = im[1:999:2]

In [88]:
print(even)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

### Multidimensional array 

In [91]:
v = np.arange(20).reshape(4,5)

In [92]:
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
v[1][2]

7

In [95]:
v[1,2]

7

In [97]:
v[1:3 , 0:3]

array([[ 5,  6,  7],
       [10, 11, 12]])

In [100]:
v[0:2,1]

array([1, 6])

In [104]:
v = v.flatten()

In [105]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [106]:
for r in v:
    print(r)
v = np.arange(20).reshape(4,5)
print(v)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [107]:
for e in v.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Copying Arrays

In [143]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [144]:
b = a

In [145]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
b is a

True

In [147]:
b = a[:]

In [182]:
b

array([2, 3, 4, 5, 6, 7])

In [183]:
b is a

False

In [184]:
b = a.copy()

In [185]:
b is a

False

In [186]:
a = np.arange(20)

In [187]:
#v = a.copy()

In [188]:
v is a

False

In [189]:
v = a

In [190]:
v is a

True

In [191]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [192]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [193]:
a is v

True

In [194]:
v is a

True

In [195]:
#v = a.copy()

In [196]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [197]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [198]:
v is a

True

In [199]:
a is v

True

In [200]:
# a.shape = (4,5)

In [201]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [202]:
v[1] = -1

In [203]:
v

array([ 0, -1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [204]:
#b = v[2:8]

In [205]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [207]:
b.base is a

False

In [208]:
a


array([ 0, -1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [209]:
c = a[:]

In [210]:
c.base is a

True

In [211]:
c is a

False

In [212]:
c.flags.owndata

False

In [213]:
a.flags.owndata

True

In [221]:
a = np.arange(12).reshape(3,4)
d = a.copy()
d[:,:] = 0.0

print(a)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## Boolean Indexing

In [222]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [223]:
a[a>4]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [226]:
a[a==0]=-1
a

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [227]:
a == -1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [228]:
a = np.arange(12).reshape(3,4)
a[np.logical_and(a>3 , a<=9)] = 0.0
a

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [229]:
a > 4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

## Avoiding Loops

In [237]:
X = 32
Y = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, X, endpoint=False)
y = np.linspace(ymin, ymax, Y, endpoint=False)

print(x.shape)
print(y.shape)
print(x)
y

(32,)
(64,)
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [239]:
import time
import numpy as np
X = 32
Y = 64

x = np.linspace(0.0, 1.0, X, endpoint=False)
y = np.linspace(0.0, 1.0, Y, endpoint=False)

In [255]:
t0 = time.time()

g = np.zeros((X,Y))

print(g)

for i in range(X):
    for j in range(Y):
        g[i, j] = np.sin(2.0*np.pi*x[i]*y[j])
        
print(g)
t1 = time.time()
print("time elapsed: {} s" .format(t1 - t0))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.00306796  0.00613588 ...  0.18605515  0.18906866
   0.1920804 ]
 [ 0.          0.00613588  0.01227154 ...  0.365613    0.37131719
   0.37700741]
 ...
 [ 0.          0.08885355  0.17700422 ... -0.75520138 -0.69397146
  -0.62725182]
 [ 0.          0.09190896  0.18303989 ... -0.62005721 -0.54532499
  -0.4659765 ]
 [ 0.          0.0949635   0.18906866 ... -0.46325978 -0.37700741
  -0.28734746]]
time elapsed: 0.007984638214111328 s


In [256]:
x2d , y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [287]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s" .format(t1-t0))

time elapsed: 0.000997304916381836 s


## NumPy standard Data types

### Array Concatenation and Splitting

In [290]:
x = np.array([1,3,5,7])
y = np.array([8,6,4,2])

np.concatenate([y,x,y])

array([8, 6, 4, 2, 1, 3, 5, 7, 8, 6, 4, 2])

In [289]:
[y,x]

[array([8, 6, 4, 2]), array([1, 3, 5, 7])]

In [291]:
z = [9,6,3]
print(np.concatenate([y,x,z]))

[8 6 4 2 1 3 5 7 9 6 3]


In [292]:
grid = np.array([[10,20,30],[60,50,40]])
np.concatenate([grid,grid])

array([[10, 20, 30],
       [60, 50, 40],
       [10, 20, 30],
       [60, 50, 40]])

In [293]:
np.concatenate([grid,grid], axis=1)

array([[10, 20, 30, 10, 20, 30],
       [60, 50, 40, 60, 50, 40]])

### Splitting Array

In [295]:
x = [1,3,5,7,8,6,4,2,9,6,3]
x1,x2,x3,x4 = np.split(x,[3,5,8])
print(x1,x2,x3,x4)

[1 3 5] [7 8] [6 4 2] [9 6 3]


In [296]:
grid = np.arange(25).reshape((5, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [297]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


### Aggregates

In [298]:
x = np.arange(1,9)
print(x)
np.add.reduce(x)

[1 2 3 4 5 6 7 8]


36

In [300]:
np.multiply.reduce(x)

40320

In [301]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [304]:
np.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320],
      dtype=int32)